name: musicflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - mido>=1.2.10
    - pretty_midi>=0.2.9
    - openai>=1.6.1
    - python-dotenv>=1.0.0
    - rich>=13.3.5
    - pytest>=7.0.0
    - black>=23.3.0
    - isort>=5.12.0
    - python-rtmidi>=1.4.9
    - python-osc>=1.8.0    # For OSC communication with Ableton